Add Counters to QuasiNewtonNLPModels
JuliaSmoothOptimizers/NLPModelsModifiers.jl pull request #122
Opened 2024-07-23 11:51 UTC by MaxenceGollier

Discussed in #121

2024-07-23 11:58 UTC, tmigot commented
@MaxenceGollier thanks for the PR. Instead of adding manually counters to all structures. Would it be sufficient to add `@default_counters AbstractDiagonalQNModel model` right after `@default_counters QuasiNewtonModel model`?

2024-07-24 16:22 UTC, MaxenceGollier commented
What do you think of this solution @tmigot ?

2024-07-25 22:36 UTC, tmigot requested changes
Thanks @MaxenceGollier ! I suggest we don't throw away this PR, but use it to add unit tests on counters  (that will be valid for the next NLPModels release).

2024-07-25 22:36 UTC, tmigot commented on test/nlp/quasi-newton.jl
> +      @test nlp.counters == nlp.model.counters
```suggestion
      @test nlp.counters == nlp.model.counters
       @test neval_obj(nlp) == neval_obj(nlp.model)
      @test neval_grad(nlp) == neval_grad(nlp.model)
      @test neval_hess(nlp) == neval_hess(nlp.model)
      @test neval_hprod(nlp) == neval_hprod(nlp.model)
```

2024-07-25 22:36 UTC, tmigot commented on src/quasi-newton.jl
> +
```suggestion
```
This is no longer needed.

2024-10-28 15:22 UTC, dpo requested changes

2024-10-28 15:22 UTC, dpo commented on test/nlp/quasi-newton.jl
> +       @test neval_obj(nlp) == neval_obj(nlp.model)
```suggestion
      @test neval_obj(nlp) == neval_obj(nlp.model)
```

2026-03-16 15:15 UTC, dpo commented
@MaxenceGollier Is this still relevant? I feel the unit tests that you added are already tested in NLPModels.jl (in the `@default_counters` unit tests)`.

2026-03-16 15:38 UTC, MaxenceGollier commented
I don't think it is.
We can close this PR now.

2026-03-16 15:38 UTC, closed without merging